name: Auto-approve and merge Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    # Only run for Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    
    steps:
      # Debug info
      - name: 🧩 Debug event
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"
          echo "PR base: ${{ github.event.pull_request.base.ref }}"
          echo "PR head: ${{ github.event.pull_request.head.ref }}"

      # Fetch Dependabot metadata
      - name: 📦 Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Auto-approve if not a major update
      - name: ✅ Auto-approve Dependabot PRs
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr review --approve "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Enable auto-merge (GitHub native)
      - name: 🔄 Enable auto-merge
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Comment on PR
      - name: 💬 Post confirmation comment
        if: success()
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" \
            --body "✅ Auto-approved. Will merge automatically once checks pass."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
