name: Auto-approve and merge Dependabot PRs

# Trigger on PR events or manual run
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, labeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Debug info to confirm workflow triggers
      - name: 🧩 Debug event
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "PR head ref: $GITHUB_REF_NAME"
          echo "PR URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$GITHUB_REF_NAME"

      # Fetch Dependabot metadata
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Auto-approve if not a major update
      - name: ✅ Auto-approve Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Auto-merge if not a major update
      - name: 🔄 Auto-merge Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "dependabot"
          MERGE_DELETE_BRANCH: "true"

      # Comment on PR for visibility
      - name: 💬 Post confirmation comment
        if: ${{ success() }}
        run: |
          gh pr comment "$GITHUB_REF_NAME" --body "✅ This Dependabot PR has been automatically approved and merged."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
